(() => {
  if(window.__QI_MULTIPLAYER_LOADED__) return;
  window.__QI_MULTIPLAYER_LOADED__=true;
  const WS_URL='wss://queer-icons-multiplayer.onrender.com';
  let ws=null,myId=null,room=null,active=false,isHost=false,seat=-1,phase='lobby';
  const originalRender=window.render,originalFight=window.fight,originalNext=window.next,originalRestart=window.restart,originalStart=window.start;
  const send=(type,data={})=>ws&&ws.readyState===1&&ws.send(JSON.stringify({type,...data}));
  const css=document.createElement('style');css.textContent=`
  .multiBox{margin-top:8px;padding:14px;border:1px solid #614272;border-radius:18px;background:#160e1d;display:grid;gap:10px}.multiRow{display:flex;gap:8px;flex-wrap:wrap}.multiRow>*{flex:1;min-width:120px}.multiBox input{width:100%;padding:12px 13px;border-radius:13px;border:1px solid #614272;background:#0e0913;color:#fff;font:inherit}.roomCode{font:900 28px/1 Georgia,serif;letter-spacing:.12em;color:#f1cf54}.multiPlayers{display:flex;gap:6px;flex-wrap:wrap}.multiStatus{color:#c9bacf;font-size:13px}.multiBadge{background:#392047;border:1px solid #624675;border-radius:999px;padding:6px 9px;font-size:12px}.onlineOnly{display:none}.multiActive .onlineOnly{display:block}.multiActive #playerCount{pointer-events:none;opacity:.55}
  `;document.head.appendChild(css);
  const setup=document.getElementById('setup');if(!setup)return;
  if(setup.querySelector('.multiBox')) return;
  const box=document.createElement('div');box.className='multiBox';box.innerHTML=`<strong>Multijoueur en ligne</strong><div class="multiRow"><input id="multiName" maxlength="24" placeholder="Ton prénom / pseudo"><input id="multiCode" maxlength="5" placeholder="Code de partie"></div><div class="multiRow"><button id="createRoom" class="secondary">Créer une partie</button><button id="joinRoom" class="secondary">Rejoindre</button></div><div id="multiLobby" class="hidden"><div class="multiStatus">Code de partie</div><div id="roomCode" class="roomCode"></div><div id="multiPlayers" class="multiPlayers"></div><div id="multiStatus" class="multiStatus"></div><button id="onlineStart" class="primary hidden">Lancer la partie en ligne</button></div>`;setup.insertBefore(box,document.getElementById('startBtn'));
  const $m=id=>document.getElementById(id);
  function connect(done){if(ws&&ws.readyState===1)return done();$m('multiStatus').textContent='Connexion au serveur…';ws=new WebSocket(WS_URL);ws.onopen=()=>done();ws.onerror=()=>{$m('multiStatus').textContent='Impossible de joindre le serveur multijoueur.'};ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}handle(m)};ws.onclose=()=>{if(active)$m('multiStatus').textContent='Connexion perdue. Recharge la page pour te reconnecter.'}}
  function name(){return $m('multiName').value.trim()||'Joueur'}
  $m('createRoom').onclick=()=>connect(()=>send('create',{name:name()}));
  $m('joinRoom').onclick=()=>{const code=$m('multiCode').value.trim().toUpperCase();if(!code)return;$m('multiCode').value=code;connect(()=>send('join',{name:name(),code}))};
  $m('onlineStart').onclick=()=>{if(!isHost||!room||room.players.length<2)return;document.getElementById('playerCount').value=String(room.players.length);active=true;phase='play';originalStart();syncPlay()};
  function handle(m){
    if(m.type==='hello'){myId=m.id;return}
    if(m.type==='error'){alert(m.message||'Erreur multijoueur');return}
    if(m.type==='room'){room=m;active=true;isHost=m.hostId===myId;seat=m.players.findIndex(p=>p.id===myId);phase=m.state?.phase||'lobby';renderLobby();if(m.state)applyState(m.state);return}
    if(m.type==='state'){applyState(m.state);return}
    if(m.type==='action'&&isHost){const sender=room?.players.findIndex(p=>p.id===m.playerId)??-1;if(m.action==='fight'&&sender===S.leader&&!S.locked){const played=S.hands.map(h=>h[0]||null);originalFight(m.payload.category);phase='result';sendState({played,table:document.getElementById('table').innerHTML,result:document.getElementById('result').innerHTML,category:m.payload.category})}else if(m.action==='next'&&S.locked&&!S.ended){originalNext();phase='play';syncPlay()}}
  }
  function renderLobby(){
    document.body.classList.add('multiActive');$m('multiLobby').classList.remove('hidden');$m('roomCode').textContent=room.code;$m('multiPlayers').innerHTML='';room.players.forEach((p,i)=>{const b=document.createElement('span');b.className='multiBadge';b.textContent=`J${i+1} · ${p.name}${p.id===room.hostId?' · HÔTE':''}`;$m('multiPlayers').appendChild(b)});$m('multiStatus').textContent=isHost?(room.players.length<2?'En attente d’au moins un autre joueur…':'Prêt à lancer la partie.'):'En attente du lancement par l’hôte…';$m('onlineStart').classList.toggle('hidden',!isHost||room.players.length<2);document.getElementById('startBtn').classList.add('hidden')
  }
  function sendState(extra={}){send('state',{state:{phase,game:S,names:room.players.map(p=>p.name),...extra}})}
  function syncPlay(){sendState();personalize()}
  function applyState(st){if(!st?.game)return;S=st.game;phase=st.phase||'play';document.getElementById('setup').classList.add('hidden');document.getElementById('game').classList.remove('hidden');originalRender();personalize(st);if(phase==='result'){document.getElementById('table').innerHTML=st.table||'';const r=document.getElementById('result');r.innerHTML=st.result||'';r.classList.remove('hidden');document.getElementById('nextBtn').classList.toggle('hidden',!isHost)}else document.getElementById('nextBtn').classList.add('hidden')}
  function personalize(st={}){
    if(!active||seat<0||!S.hands?.[seat])return;const card=phase==='result'?(st.played?.[seat]||S.hands[seat][0]):S.hands[seat][0];if(!card)return;const names=st.names||room?.players.map(p=>p.name)||[];document.getElementById('leader').textContent=names[S.leader]||`J${S.leader+1}`;document.getElementById('cardName').textContent=card.name;document.getElementById('modifier').textContent=(card.modifier||'')+(S.mode==='blind'?' · MODE AVEUGLE':S.mode==='superblind'?' · MODE SUPER AVEUGLE':S.mode==='drunken'?' · RANDOM DRUNKEN HOOKUP':'');const img=document.getElementById('portraitImg'),fb=document.getElementById('portraitFallback');img.classList.remove('hidden');fb.classList.add('hidden');img.alt=card.name;img.src=resolveImagePath(card.image);img.onerror=()=>{img.classList.add('hidden');fb.textContent=initials(card.name);fb.classList.remove('hidden')};const stats=document.getElementById('stats');stats.innerHTML='';const cats=S.mode==='drunken'?S.randomCats:CATEGORIES;cats.forEach(cat=>{const meta=CATEGORY_META.find(x=>x.name===cat),row=document.createElement('div'),b=document.createElement('button'),sc=document.createElement('span');row.className='stat';['cat','cat-soft','cat-faint','cat-dark'].forEach((k,i)=>row.style.setProperty('--'+k,[meta.color,meta.soft,meta.faint,meta.dark][i]));b.type='button';b.className='statbutton';const showComment=S.mode!=='superblind',comment=showComment?(card.comments?.[cat]||''):'';b.innerHTML=`<span class="catIcon"><img src="${meta.icon}" alt=""></span><span class="statText"><span class="statName">${cat}</span>${showComment?`<span class="statComment">${comment}</span>`:''}</span>`;const canChoose=phase==='play'&&seat===S.leader&&!S.locked;b.disabled=!canChoose;b.onclick=()=>onlineFight(cat);sc.className='score';sc.textContent=S.mode==='classic'?card.scores[cat]:'?';row.append(b,sc);stats.append(row)});document.getElementById('players').innerHTML='';S.hands.forEach((h,i)=>{const x=document.createElement('span');x.className='badge';x.textContent=`${names[i]||`J${i+1}`} · ${h.length} carte${h.length>1?'s':''}${i===S.leader?' · LEADER':''}${i===seat?' · TOI':''}`;document.getElementById('players').append(x)})
  }
  function onlineFight(cat){if(!active)return originalFight(cat);if(seat!==S.leader||S.locked)return;if(isHost){const played=S.hands.map(h=>h[0]||null);originalFight(cat);phase='result';sendState({played,table:document.getElementById('table').innerHTML,result:document.getElementById('result').innerHTML,category:cat})}else send('action',{action:'fight',payload:{category:cat}})}
  window.fight=onlineFight;
  document.getElementById('nextBtn').addEventListener('click',e=>{if(!active)return;e.preventDefault();e.stopImmediatePropagation();if(isHost){originalNext();phase='play';syncPlay()}else send('action',{action:'next'})},true);
  document.getElementById('restartBtn').addEventListener('click',e=>{if(!active)return;e.preventDefault();e.stopImmediatePropagation();location.reload()},true);
})();
